version: '3.8'

services:
  ai-takeoff-api:
    build: .
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - CONVERTIO_API_KEY=${CONVERTIO_API_KEY}
      - GOOGLE_DRIVE_API_KEY=${GOOGLE_DRIVE_API_KEY}
    volumes:
      - ai_takeoff_files:/app/files
      - ai_takeoff_data:/app/data.json
      - ai_takeoff_config:/app/utils/config.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

volumes:
  ai_takeoff_files:
  ai_takeoff_data:
  ai_takeoff_config:
