[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python main.py"
# healthcheckPath = "/health"  # Disabled
# healthcheckTimeout = 100    # Disabled
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

